common/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('header', views.HeaderView.as_view(), name="header"),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('contact/',  views.ContactView.as_view(), name='contact'),
]

myDjango21/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('user.urls')),
    path('', include('post.urls')),
    path('', include('contact.urls')),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/',  views.RegisterView.as_view(), name='register'),
    path('doublecheck/', views.doubleCheck, name="doubleCheck"),
    path('login/',  views.LoginView.as_view(), name='login'),
    path('logout/',  views.LogoutView.as_view(), name='logout'),
]

common/models.py
from django.db import models

# Create your models here.

contact/models.py
import os
from django.conf import settings
from django.db import models

class Contact(models.Model):
    email = models.EmailField(verbose_name='이메일')
    content = models.TextField(verbose_name='내용')

    def __str__(self):
        return self.email

    class Meta:
        db_table = 'contact_table'
        verbose_name = 'contact'
        verbose_name_plural = 'contacts'

post/models.py
import os
from django.conf import settings
from django.db import models

class Post(models.Model):
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, verbose_name='작성자')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'post_table'
        verbose_name = 'post'
        verbose_name_plural = 'posts'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class UserManager(BaseUserManager):
    def create_user(self, user_id, password, email):
        user = self.model(
            user_id = user_id,
            email = email,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password, email=None):
        user = self.create_user(user_id, password, email)
        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.save(using=self._db)
        return user
    
class User(AbstractBaseUser, PermissionsMixin):
    
    objects = UserManager()

    user_id = models.CharField(max_length=17, verbose_name="아이디", unique=True)
    password = models.CharField(max_length=256, verbose_name="비밀번호")
    email = models.EmailField(max_length=128, verbose_name="이메일",null=True, blank=True)


    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일', null=True, blank=True)

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['email']
    
    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "user_table"
        verbose_name = "user"
        verbose_name_plural = "users"

common/views.py
import json

from django.views import View
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.contrib.auth.decorators import login_required
# Create your views here.

class IndexView(View):

    def get(self, request): 
        return render(request, 'common/index.html')

class HeaderView(View):

    def get(self, request): 
        return render(request, 'common/header.html')

contact/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse

from .models import Contact


class ContactView(View):
    
    def post(self, request):
        try:
            data = request.POST
            
            contact = Contact(
                email=data.get('email', None),
                content=data.get('content', None),
            )
            
            contact.save()
            return JsonResponse({'msg': "success"}, status=200)
            
        except KeyError:
            return JsonResponse({'msg': "INVALID_KEYS"}, status=400)

    def get(self, request):
        return render(request, 'contact/index.html', {})

post/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
import json

from django.views import View
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse


from .models import User
from django.contrib import auth



class RegisterView(View):
    def post(self, request):
        try:
            data = request.POST
            
            user = User.objects.create_user(
                        user_id=data.get('user_id', None),
                        password=data.get('user_pw', None),
                        email='test'
                    )
            
            auth.login(request, user)
            return JsonResponse({'msg': "success"}, status=200)
            
        except KeyError:
            return JsonResponse({'msg': "INVALID_KEYS"}, status=400)
    
    
    def get(self, request):
        
        return render(request, 'user/register.html', {})
        


class RegisterFormView(View):

    def post(self, request):
        try:
            data = request.POST
            
            user = User.objects.create_user(
                        user_id=data.get('user_id', None),
                        password=data.get('user_pw', None),
                    )
            
            auth.login(request, user)
            return JsonResponse({'msg': "success"}, status=200)
            
        except KeyError:
            return JsonResponse({'msg': "INVALID_KEYS"}, status=400)


    def get(self, request):

        return render(request, 'user/register-form.html', {})


def doubleCheck(request):
        try:
            data = request.POST
            
            if User.objects.filter(user_id=data.get('user_id', None)).exists():
                return JsonResponse({'msg': "fail"}, status=200)
          
            else:
                return JsonResponse({'msg': "success"}, status=200)
            
        except KeyError:
            return JsonResponse({'msg': "INVALID_KEYS"}, status=400)
    
    
class LoginView(View):
    
    def post(self, request):
        try:
            data = request.POST
            
            user = auth.authenticate(request, user_id=data.get('user_id', None), password=data.get('user_pw', None))
            
            if user is not None:
                auth.login(request, user)
                return JsonResponse({'msg': "success"}, status=200)
            else:
                return JsonResponse({'msg': "fail"}, status=200)

        except KeyError:
            return JsonResponse({'msg': "INVALID_KEYS"}, status=400)
    def get(self, request):

        return render(request, 'user/login.html', {})


class LogoutView(View):
    
    def get(self, request):
        auth.logout(request)
        return redirect("/")

templates/common/401.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    401페이지!!!!!!
</body>

</html>

templates/common/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/all.css">
    <link rel="stylesheet" href="/static/css/common/style.css">
    <link rel="stylesheet" href="/static/css/common/header.css">
    <link rel="stylesheet" href="/static/css/common/sidebar.css">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">
    <title>Document</title>
</head>



<body>
    <style>
        .show {
            display: flex;
        }
    </style>

    <div id="header">
        <div id="header__menu">
            <i class="fas fa-bars" id="header__menu__icon"></i>
        </div>
        <div id="header__logo" onclick="window.location.href='/'">BrandName</div>
        <div id="header__user">
            <div id="header__user__login" onclick="window.location.href='/login'">Login</div>
            <div id="header__user__register" onclick="window.location.href='/register'">Sign in</div>
        </div>

    </div>

    <div id="sidebar">
        <div id="sidebar__side">
            <div id="sidebar__side__backspace">
                <i class="sidebar__side__icon fas fa-arrow-left"></i>
            </div>

            <div class="sidebar__side__item" data-side="home" onclick="window.location.href='/'">
                <i class="sidebar__side__item__icon fas fa-home" data-side="home"></i>
            </div>


            <div class="sidebar__side__item sidebar__side__item__active" data-side="user">
                <i class="sidebar__side__item__icon fas fa-user sidebar__side__item__active" data-side="user"></i>
            </div>
            <div class="sidebar__side__item" data-side="setting">
                <i class="sidebar__side__item__icon fas fa-cog" data-side="setting"></i>
            </div>
            <div class="sidebar__side__item" data-side="notification">
                <i class="sidebar__side__item__icon far fa-bell" data-side="notification"></i>
            </div>

            <div class="sidebar__side__item" data-side="contact">
                <i class="sidebar__side__item__icon fas fa-envelope" data-side="contact"></i>
            </div>
        </div>

        <div id="sidebar__body">
            <div id="sidebar__body__item">
                <div id="sidebar__body__item__contact">
                    <div id="sidebar__body__item__contact__contact" onclick="window.location.href='/contact'">
                        Contact
                    </div>
                </div>
                <div id="sidebar__body__item__contact">
                    <div id="sidebar__body__item__contact__contact" onclick="window.location.href='/contact'">
                        Contact
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- script -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="/static/js/common/common.js"></script>
    <script src="/static/js/common/header.js"></script>
    <!--  -->
    {% if user.is_authenticated %}
    {% endif %}
    {% block content %}
    {% endblock %}

    <!--     <button id="testbtn"> 테스트 버튼입니다!</button> -->



</body>

</html>

templates/common/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/all.css">
    <link rel="stylesheet" href="/static/css/common/style.css">
    <link rel="stylesheet" href="/static/css/common/header.css">
    <link rel="stylesheet" href="/static/css/common/sidebar.css">
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    <title>Document</title>
</head>

<body>
    <style>
        .show {
            display: flex;
        }
    </style>

    <div id="header">
        <div id="header__menu">
            <i class="fas fa-bars" id="header__menu__icon"></i>
        </div>
        <div id="header__logo">BrandName</div>
        <div id="header__user">
            <div id="header__user__login"><a href="/login">LOGIN</a></div>
        </div>
    </div>

    <div id="sidebar">
        <div id="sidebar__side">

            <div id="sidebar__side__backspace">
                <i class="sidebar__side__icon fas fa-arrow-left"></i>
            </div>
            <div class="sidebar__side__item sidebar__side__item__active" data-side="user">
                <i class="sidebar__side__item__icon fas fa-user sidebar__side__item__active" data-side="user"></i>
            </div>
            <div class="sidebar__side__item" data-side="setting">
                <i class="sidebar__side__item__icon fas fa-cog" data-side="setting"></i>
            </div>
            <div class="sidebar__side__item" data-side="notification">
                <i class="sidebar__side__item__icon far fa-bell" data-side="notification"></i>
            </div>

        </div>
    </div>


    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="/static/js/common/common.js"></script>
    <script src="/static/js/common/header.js"></script>
</body>

</html>

templates/common/index.html
{% extends 'common/base.html' %}
{% block content %}
{% endblock %}

templates/contact/index.html
{% extends 'common/base.html' %}


{% block content %}
<link rel="stylesheet" href="/static/css/contact/contact.css">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<div id="contact">
    <form id="contact__form">
        <div id="contact__form__title">Let's talk</div>
        <div id="contact__form__description">
            Contact us directily or fill out the form and we will
            get back to you promptly.
        </div>

        <div id="contact__form__email">
            <div id="contact__form__email__label">Your Email</div>
            <input type="text" id="contact__form__email__input" class="contact__form__input">
        </div>
        <div id="contact__form__msg">
            <div id="contact__form__msg__label">Your Message</div>
            <textarea name="" id="contact__form__msg__input" cols="30" rows="10"
                class="contact__form__input"></textarea>

        </div>
        <div id="contact__form__submit">Send Message</div>
    </form>


    <div id="contact__info">
        <img src="/static/img/email.svg" alt="" id="contact__info__img">
        <div id="contact__info__email"><i class="fas fa-envelope"></i>mydjnago@mydjango.com</div>
        <div id="contact__info__tel"><i class="fas fa-phone-alt"></i>+82 10-1234-5678</div>
    </div>
</div>

<script>

    function validateEmail(email) {
        let re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
        return re.test(email);
    }

    let email_input = document.getElementById("contact__form__email__input")
    let msg_input = document.getElementById("contact__form__msg__input")
    let submit_btn = document.getElementById("contact__form__submit")



    submit_btn.addEventListener('click', () => {

        if (email_input.value == "" || msg_input.value == "") {
            return false
        }

        if (!(validateEmail(email_input.value))) {
            Swal.fire("이메일 주소를 확인해주세요", "", "error")
            return false
        }

        $.ajax({
            type: "post",
            dataType: "json",
            data: {
                email: email_input.value,
                content: msg_input.value,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            url: "{% url 'contact:contact' %}",
            success: function (response) {
                if (response.msg == "success") {
                    Swal.fire({
                        position: "top",
                        icon: "success",
                        title: "메세지가 전송되었습니다.",
                        showConfirmButton: false,
                        timer: 1500,
                    }).then(() => {
                        window.location.href = "/"
                    })
                } else {
                    Swal.fire("이런...", "오류 발생", "error")
                    console.log(response)
                }
            },
            error: function () {
                Swal.fire("이런...", "예상치 못한 오류가 발생했습니다!", "error")
            }
        })
    })
</script>

{% endblock %}

templates/user/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    인덱스 페이지입니다.
</body>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    console.log("인덱스 페이지")
</script>

</html>

templates/user/login.html
{% extends 'common/base.html' %}


{% block content %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<link rel="stylesheet" href="/static/css/all.css">
<link rel="stylesheet" href="/static/css/bootstrap.css">
<link rel="stylesheet" href="/static/css/user/login.css">

<div id="login">
    <div id="login__form">
        <div id="login__form__title">LOGIN</div>
        <div id="login__form__input">
            <form action="">
                <input id="login__form__input__id" type="text" class="form-control" placeholder="username" required
                    autocomplete="off" />
                <input id="login__form__input__pw" type="password" class="form-control" name="user_pw"
                    placeholder="password" required autocomplete="off" />
            </form>
        </div>
        <div id="login__form__option">
            <div id="login__form__option__remember">
                <div id="login__form__option__remember__checkbox">
                    <i id="login__form__option__remember__checkbox__icon" class="fas fa-check"></i>
                </div>
                <div> &nbsp;&nbsp;Remember me</div>
            </div>
            <div id="login__form__option__forget">
                Forgot password?
            </div>
        </div>

        <div id="login__form__submit">Login</div>


        <div id="login__form__yet">
            Don't have an account?
            <a href="/register">
                <div id="login__form__yet__register">&nbsp;&nbsp;Sign up</div>
            </a>
        </div>

    </div>

</div>


<script>

    let submitBtn = document.getElementById('login__form__submit')

    submitBtn.addEventListener('click', () => {
        $.ajax({
            type: "post",
            dataType: "json",
            data: {
                user_id: document.getElementById('login__form__input__id').value,
                user_pw: document.getElementById('login__form__input__pw').value,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            url: "{% url 'user:login' %}",
            success: function (response) {
                if (response.msg == "success") {
                    location.href = "/"
                } else {
                    Swal.fire("이런...", "아이디나 비밀번호를 다시 확인하세요", "error")
                    console.log(response)
                }
            },
            error: function () {
                Swal.fire("이런...", "예상치 못한 오류가 발생했습니다!", "error")
            }
        })
    })

</script>
{% endblock %}

templates/user/register.html
{% extends 'common/base.html' %}


{% block content %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="/static/js/common/common.js"></script>
<link rel="stylesheet" href="/static/css/all.css">
<link rel="stylesheet" href="/static/css/bootstrap.css">
<link rel="stylesheet" href="/static/css/user/register.css">

<div id="register">
    <div id="register__form">
        <div id="register__form__title">Sign Up</div>
        <div id="register__form__input">
            <form>
                {% csrf_token %}
                <div style="margin-top: 20px;">
                    <label style=" font-weight: 600;">아이디</label>
                </div>
                <div class="input-group">
                    <input id="register__form__input__id" type="text" class="form-control" placeholder="아이디를 입력해 주세요."
                        autocomplete="off" aria-describedby="register__form__input__id__double" />
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="register__form__input__id__double">
                            중복 확인
                        </button>
                    </div>
                    <div class="valid-feedback">
                        <p style=" margin-top: 0.5vh;">좋습니다!</p>
                    </div>
                    <div class="invalid-feedback">
                        <p id="notice-id" style=" margin-top: 0.5vh;">
                            소문자 영문, 숫자로 조홥된 6~14자리를 입력해 주세요.
                        </p>
                    </div>
                </div>

                <!-- 비밀번호 -->
                <div style="margin-top: 10px;">
                    <label style=" font-weight: 600;">
                        비밀번호</label>
                    <input type="password" class="form-control" id="register__form__input__pw"
                        placeholder="비밀번호를 입력해 주세요." autocomplete="off" required="required" />
                    <div class="valid-feedback">
                        <p style=" margin-top: 0.5vh;">좋습니다!</p>
                    </div>
                    <div class="invalid-feedback">
                        <p style=" margin-top: 0.5vh;">
                            대소문자 영문, 숫자로 조합된 7~20자리를 입력해 주세요.
                        </p>
                    </div>
                </div>
                <!-- 비밀번호 확인-->
                <div style="margin-top: 10px;">
                    <label style=" font-weight: 600;">
                        비밀번호 확인</label>
                    <input type="password" class="form-control" id="register__form__input__pw__re"
                        placeholder="비밀번호를 다시 입력해 주세요." autocomplete="off" required="required" />
                    <div class="valid-feedback">
                        <p style=" margin-top: 0.5vh;">좋습니다!</p>
                    </div>
                    <div class="invalid-feedback">
                        <p style=" margin-top: 0.5vh;">비밀번호를 다시 확인해 주세요.</p>
                    </div>
                </div>
            </form>
        </div>
        <div id="register__form__option">
            <div id="register__form__option__terms">
                <div id="register__form__option__terms__checkbox">
                    <i id="register__form__option__terms__checkbox__icon" class="fas fa-check"></i>
                </div>
                <div> &nbsp;&nbsp;I have read and agree to the <span style="color: #334ACF; font-weight: 500;"
                        onclick="window.location.href='/'">Terms of
                        Serivece</span>
                </div>
            </div>
        </div>
        <button type="button" class="btn btn-primary btn-lg btn-block" disabled="disabled" id="register__form__submit">
            Sign up
        </button>



        <div id="register__form__already">
            Already registered?
            <div id="register__form__already__login" onclick="window.location.href='/login'">&nbsp;&nbsp;Login</div>
        </div>


    </div>

</div>








<script>
    function isValidId(str) {
        let reg = /^[a-z0-9]{6,14}$/ // a~z 0~9 6~14자리
        return reg.test(str)
    }
    function isValidPw(str) {
        let reg = /^(?=.*[a-zA-Z])((?=.*\d)|(?=.*\W)).{7,20}$/ // 영문 숫자 특수문자 중 2개 조합 7~20자리
        return reg.test(str)
    }

    function setValidFeedback(element) {
        element.addClass("is-valid")
        element.removeClass("is-invalid")
    }

    function setInvalidFeedback(element) {
        element.addClass("is-invalid")
        element.removeClass("is-valid")
    }


    $(document).ready(function () {
        let flag__terms = 0
        let doubelChecked = 0
        let register__form__input__id = $("#register__form__input__id")
        let register__form__input__pw = $("#register__form__input__pw")
        let register__form__input__pw__re = $("#register__form__input__pw__re")
        let doubleCheck = $("#register__form__input__id__double")
        let submitBtn = $("#register__form__submit")

        register__form__input__id.val("")
        register__form__input__id.focus()

        register__form__input__id.on("change", function () {
            if (!isValidId(register__form__input__id.val())) {
                setInvalidFeedback(register__form__input__id)
            }
            else {
                register__form__input__id.removeClass("is-invalid")
            }
        })
        register__form__input__pw.on("keyup", function () {
            if (isValidPw(register__form__input__pw.val())) {
                setValidFeedback(register__form__input__pw)
            } else {
                setInvalidFeedback(register__form__input__pw)
            }
            if (register__form__input__pw__re.val()) {
                if (register__form__input__pw__re.val() == register__form__input__pw.val()) {
                    setValidFeedback(register__form__input__pw__re)
                } else {
                    setInValidFeedback(register__form__input__pw__re)
                }
            }
        })
        register__form__input__pw__re.on("keyup", function () {
            if (register__form__input__pw__re.val() == register__form__input__pw.val()) {
                setValidFeedback(register__form__input__pw__re)
            } else {
                setInvalidFeedback(register__form__input__pw__re)
            }
        })



        $("input").on("keyup", function () {
            let isIdChecked = register__form__input__id.hasClass("is-valid")
            let isPwChecked = register__form__input__pw.hasClass("is-valid")
            let isPwReChecked = register__form__input__pw__re.hasClass("is-valid")
            if (isIdChecked && isPwChecked && isPwReChecked && doubelChecked && flag__terms) {
                submitBtn.prop("disabled", false)
            } else {
                submitBtn.prop("disabled", true)
            }
        })



        /* TERMS */
        let register__form__option__terms = document.getElementById("register__form__option__terms");
        register__form__option__terms.addEventListener("click", () => {
            if (flag__terms) {
                hide(document.getElementById("register__form__option__terms__checkbox__icon"))
                document.getElementById("register__form__option__terms__checkbox").style.backgroundColor = "#fff"
                document.getElementById("register__form__option__terms__checkbox").style.border = "1px solid darkgray"
                submitBtn.prop("disabled", true)
                flag__terms = 0
            }
            else {
                block(document.getElementById("register__form__option__terms__checkbox__icon"))
                document.getElementById("register__form__option__terms__checkbox").style.backgroundColor = "#334ACF"
                document.getElementById("register__form__option__terms__checkbox").style.border = "none"
                flag__terms = 1


                let isIdChecked = register__form__input__id.hasClass("is-valid")
                let isPwChecked = register__form__input__pw.hasClass("is-valid")
                let isPwReChecked = register__form__input__pw__re.hasClass("is-valid")
                if (isIdChecked && isPwChecked && isPwReChecked && doubelChecked && flag__terms) {
                    submitBtn.prop("disabled", false)
                } else {
                    submitBtn.prop("disabled", true)
                }

            }
        })




        // 중복확인
        doubleCheck.on("click", function () {
            if (!isValidId(register__form__input__id.val())) { // 아이디가 부적절하면 ajax 요청 안함
                doubleCheck.css("background-color", "white")
                doubleCheck.css("color", "black")
                return false
            }
            $.ajax({
                type: "post",
                dataType: "json",
                data: {
                    user_id: register__form__input__id.val(),
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                url: "{% url 'user:doubleCheck' %}",
                success: function (response) {
                    if (response.msg == "success") {
                        doubelChecked = 1
                        doubleCheck.css("background-color", "green")
                        doubleCheck.css("color", "white")
                        setValidFeedback(register__form__input__id)
                        register__form__input__id.prop("disabled", true)
                        doubleCheck.prop("disabled", true)
                        Swal.fire({
                            position: "top",
                            icon: "success",
                            title: "중복 확인 완료",
                            showConfirmButton: false,
                            timer: 1000,
                        })
                    }
                    else {
                        doubelChecked = 0
                        Swal.fire({
                            position: "top",
                            icon: "error",
                            title: "해당 아이디는 이미 사용하고 있습니다.",
                            showConfirmButton: false,
                            timer: 1000,
                        })
                    }
                },
                error: function (error) {
                    alert("에러 발생")
                    console.log(error)
                }
            })
        })

        submitBtn.on("click", function () {
            $.ajax({
                type: "post",
                dataType: "json",
                data: {
                    user_id: register__form__input__id.val(),
                    user_pw: register__form__input__pw.val(),
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                url: "{% url 'user:register' %}",
                success: function (response) {
                    if (response.msg == "success") {
                        Swal.fire({
                            icon: "success",
                            title: "회원가입이 완료되었습니다",
                            showConfirmButton: false,
                            timer: 1500
                        }).then(function () {
                            location.href = "/"
                        })
                    } else {
                        Swal.fire("이런...", "예상치 못한 오류가 발생했습니다", "error")
                        console.log(response)
                    }
                },
                error: function () {
                    Swal.fire("이런...", "예상치 못한 오류가 발생했습니다!", "error")
                }
            })
        })


    })




</script>


{% endblock %}